service:
  name: requestbin

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-cloudfront-lambda-edge

provider:
  name: aws
  runtime: nodejs6.10

functions:
  requestbin:
    handler: index.handler 
    events:
      - http:
          method: any
          path: /
  s3auth:
    handler: s3auth.handler
    events:
      - lambdaAtEdge:
          distribution: 'requestbin'
          eventType: 'origin-request'
